# Application Dockerfile
FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./


# Install dependencies
RUN npm install

# Copy the application code
COPY . .
ARG NODE_PORT
# Expose the port your application runs on
EXPOSE ${NODE_PORT}

# Define the command to run the application
CMD [ "npm", "start" ]