# PostgreSQL Dockerfile
FROM postgres:15

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=Str0ngP@ssw0rd
ENV POSTGRES_DB=nest

# Expose the default PostgreSQL port
EXPOSE 5432