# Application Dockerfile
FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .

# Expose the port your application runs on
EXPOSE 3000

# Define the command to run the application
CMD ["npm", "start"]